# Generated by Django 4.0.6 on 2022-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
